version: "3.7"
services:
  redis:
    image: "redis:5.0.3-alpine"
    restart: always
    ports:
      - "6379:6379"
  redis_commander:
    image: 'rediscommander/redis-commander'
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
